# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 19:43
from __future__ import unicode_literals

import custom_fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=16)),
                ('on_poloniex', models.BooleanField(default=False)),
                ('on_coinbase', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DynamicTradeSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_trade', models.BooleanField(default=False)),
                ('trade_limit', custom_fields.BitcoinField(decimal_places=8, default=0, max_digits=16)),
                ('can_buy', models.BooleanField(default=False)),
                ('can_sell', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamic_settings.Coin')),
            ],
        ),
    ]
