# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 23:48
from __future__ import unicode_literals

from django.db import migrations, models
import rainmaker.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LendHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', rainmaker.models.BitcoinField(decimal_places=8, default=0, max_digits=16)),
                ('interest_ask', models.DecimalField(decimal_places=6, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LendStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_interest_ask', models.DecimalField(decimal_places=8, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
